####################
# Generated by ZodToPython
# DO NOT MODIFY
####################


from dataclasses import dataclass
from typing import Optional

@dataclass
class Team:
    name: str
    members: list[str]
    description: str
    user: Optional[str]