####################
# Generated by ZodToPython
# DO NOT MODIFY
####################


from dataclasses import dataclass

@dataclass
class Team:
    name: str
    members: list[str]
    description: Literal["asd"]
    user: Optional[str]Team