####################
# Generated by Zod2Py
# DO NOT MODIFY
####################

from typing import Literal
from typing import Optional
from dataclasses import dataclass

@dataclass
class Team:
    name: str
    members: list[str]
    description: Literal["asd"]
    user: Optional[str]
